include(${CMAKE_CURRENT_LIST_DIR}/pal_add_config.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pal_add_compilation_test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pal_find_python_module.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pal_print_banner.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pal_print_usage.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pal_run_generator.cmake)
