function(pal_print_usage)
    if(CMAKE_GENERATOR STREQUAL "Unix Makefiles")
        set(BUILD_COMMAND "make")
    elseif(CMAKE_GENERATOR STREQUAL "Ninja")
        set(BUILD_COMMAND "ninja")
    elseif(CMAKE_GENERATOR STREQUAL "NMake")
        set(BUILD_COMMAND "nmake")
    elseif(CMAKE_GENERATOR STREQUAL "Visual Studio 14 2015 Win64")
        set(BUILD_COMMAND "msbuild hypervisor.sln")
    elseif(CMAKE_GENERATOR STREQUAL "Visual Studio 15 2017 Win64")
        set(BUILD_COMMAND "msbuild hypervisor.sln")
    else()
        message(FATAL_ERROR "Unsupported cmake generator: ${CMAKE_GENERATOR}")
    endif()

    message(STATUS "${Green} PAL is ready to build, usage:${ColorReset}")
    message(STATUS "${Yellow}    ${BUILD_COMMAND}${ColorReset}")
    message(STATUS "")
endfunction(pal_print_usage)
