function(pal_print_usage)
    message(STATUS "${Green} PAL is ready to build, usage:${ColorReset}")
    message(STATUS "${Yellow}    ${BUILD_COMMAND}${ColorReset}")
    message(STATUS "")
endfunction(pal_print_usage)
