function(pal_print_banner)
    message(STATUS "${BoldMagenta}     _______  _______  _            _ ${ColorReset}")
    message(STATUS "${BoldMagenta}    (  ____ )(  ___  )( \\          ( \\  ${ColorReset}")
    message(STATUS "${BoldMagenta}    | (    )|| (   ) || (         _ \\ \\ ${ColorReset}")
    message(STATUS "${BoldMagenta}    | (____)|| (___) || |        (_) ) )${ColorReset}")
    message(STATUS "${BoldMagenta}    |  _____)|  ___  || |            | |${ColorReset}")
    message(STATUS "${BoldMagenta}    | (      | (   ) || |         _  ) )${ColorReset}")
    message(STATUS "${BoldMagenta}    | )      | )   ( || (____/\\  (_)/ / ${ColorReset}")
    message(STATUS "${BoldMagenta}    |/       |/     \\|(_______/    (_/  ${ColorReset}")
    message(STATUS "  The Bareflank ${BoldMagenta}P${ColorReset}rocessor ${BoldMagenta}A${ColorReset}bstraction ${BoldMagenta}L${ColorReset}ayer")
    message(STATUS "")
endfunction(pal_print_banner)
