name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm build-essential g++-arm-linux-gnueabihf g++-aarch64-linux-gnu
        sudo apt-get install -y python3 linux-headers-$(uname -r)
        sudo pip3 install lxml colorama dataclasses pyyaml

    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DPAL_TEST=ON -DPAL_EXAMPLE=ON -DPAL_C=ON -DPAL_C++11=ON -DPAL_DRIVER=ON -DPAL_INTEL_64BIT_LINUX_IOCTL=ON -DPAL_INTEL_64BIT_SYSTEMV_GNUINLINE=ON -DPAL_INTEL_64BIT_SYSTEMV_NASM=ON -DPAL_PCIE=ON -DPAL_ACPI=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build .
